moveit/moveit2_tutorials

- _themes/sphinx_rtd_theme/breadcrumbs.html
This fixes issue #44 
According to the [python_documentation](https://docs.python.org/3.7/library/2to3.html?highlight=viewkeys#2to3fixer-dict) `dict.viewkeys()` has been changed to `dict.keys()` (which I found answered in this stack overflow question [here](https://stackoverflow.com/questions/57358384/python-dict-object-has-no-attribute-viewkeys))
> Fix build_localy.sh

- README.md
- moveit2_tutorials.repos
This PR pulls a local copy of `rosdoc_lite` and `genmsg` so that the user can deploy the webpage and generate the html pages locally.
> Enable ros2 deploy

- .travis.yml
- build_locally.sh
- htmlproofer.sh
- moveit2_tutorials.repos
The PR re-orders the travis scrip to call `htmlproofer.sh`
> Enable travis to call htmlproofer.sh

- package.xml
> Add dependency on moveit_resources_panda_moveit_config. 

- doc/kinematics_configuration/kinematics_configuration_tutorial.rst
Copy part of the docs for the Cached IK plugin to the tutorials.
See also https://github.com/ros-planning/moveit_tutorials/pull/622
> add docs for cached ik plugin

- .travis.yml
We need to enable `Build pushed branches` from Travis to deploy the website on new commits, this PR will restrict the deployment to only use the main branch
> Enable building only main branch

- doc/getting_started/getting_started.rst
adds missing step to Foxy source install instructions: https://github.com/ros-planning/moveit2/issues/438#issuecomment-826421039 @tylerjw
> Adds git clone ros-planning/moveit2.git to install

- doc/planning_scene_ros_api/src/planning_scene_ros_api_tutorial.cpp
In the planning scene ROS API tutorial, the text states that updates to the planning scene can be made synchronously, then gives an asynchronous example. Changed the example to use a synchronous update.
> Fixed async call that was supposed to be synchronous in planning_scene_ros_api_tutorial.cpp

- doc/getting_started/getting_started.rst
Adds a git clone command for moveit2_tutorials on the getting started page. The [first tutorial](http://moveit2_tutorials.picknik.ai/doc/quickstart_in_rviz/quickstart_in_rviz_tutorial.html#step-1-launch-the-demo-and-configure-the-plugin) references this package, but it wouldn't be available based on the current instructions (assuming I didn't make a mistake).
> Add git clone moveit2_tutorials in getting_started.rst

- doc/move_group_interface/move_group_interface_tutorial.rst
The launch file link to the repo was just missing the ".py".
- [ x ] **Required by CI**: Code is auto formatted using [clang-format](http://moveit.ros.org/documentation/contributing/code)
- [ x ] While waiting for someone to review your request, please consider reviewing [another open pull request](https://github.com/ros-planning/moveit2/pulls) to support the maintainers
> Fixed broken link to launch file

- doc/realtime_servo/launch/servo_teleop.launch.py
The `/`'s on the parameter names broke the parameters and caused the Static TF publisher to use default values, which broke the TF tree. See attached. Now the Servo demo launches with the `/world` frame known in the TF tree
Before:
[frames_sad.pdf](https://github.com/ros-planning/moveit2_tutorials/files/6976654/frames_sad.pdf)
After:
[frames_happy.pdf](https://github.com/ros-planning/moveit2_tutorials/files/6976657/frames_happy.pdf)
> Fix parameter names on Servo Teleop Demo: StaticTransformBroadcasterNode

- package.xml
These dependencies had to be installed when I tried doing the first tutorial without installing moveit from source and instead using rosdep to install dependencies of this package.
> Add missing depdendencies

- .github/workflows/industrial_ci_action.yml
Our ccache is broken in CI, thus our ccache action should be updated to match Github's new ccache action v2 as per https://github.com/ros-planning/moveit2/pull/619
> Fix ccache

- doc/move_group_interface/launch/move_group.launch.py
- doc/moveit_cpp/launch/moveit_cpp_tutorial.launch.py
- doc/quickstart_in_rviz/launch/demo.launch.py
- doc/realtime_servo/launch/servo_cpp_interface_demo.launch.py
- doc/realtime_servo/launch/servo_server_panda.launch.py
- doc/realtime_servo/launch/servo_teleop.launch.py
- package.xml
With ros-controls/ros2_controllers#230 ros2_control now removed joint_state_controller in favor of joint_state_broadcaster. This PR migrates our main branch to joint_state_broadcaster. Depends on ros-planning/moveit_resources#96.
> Migrate to joint state broadcaster

- moveit2_tutorials.repos
Potentially fixes issue #114
Currently, in Foxy, the repositories **moveit2_tutorials** and   **moveit_resources** are out of synch.
A more conservative approach would be to add this repository to **moveit2_tutorials.repos**
> Clone repository ros-planning/moveit_resources to fix issue #114

- doc/move_group_interface/move_group_interface_tutorial.rst
As the next button now works in the rviz_visual_tools, we no longer need these sections of the instructions.
> No longer require xterm

- doc/move_group_interface/launch/move_group.launch.py
- doc/moveit_cpp/launch/moveit_cpp_tutorial.launch.py
- doc/quickstart_in_rviz/launch/demo.launch.py
- doc/realtime_servo/launch/servo_server_panda.launch.py
- doc/realtime_servo/launch/servo_teleop.launch.py
Fix this warning:
`[ros2 run controller_manager spawner.py panda_arm_controller-7] /home/andy/ws_ros2/install/controller_manager/lib/controller_manager/spawner.py:186: DeprecationWarning: 'spawner.py' is deprecated, please use 'spawner' (without .py extension)`
> Find/replace deprecated spawner.py

- CMakeLists.txt
Without this the directory doesn't build and therefore the tutorial is broken.  This also sorts the calls to add_subdirectory.
> Add moveit_cpp subdirectory to cmake

- .github/workflows/ci_main.yml
I don't really know what I'm doing with CI so please double-check this.
I just created a Galactic branch. Thus, Galactic CI should not be running for the main branch anymore. I hope this removes it.
> Do not run the Galactic CI job on main branch

- _themes/sphinx_rtd_theme/layout.html
- doc/move_group_interface/move_group_interface_tutorial.rst
This fixes the name of the package in a couple places to be moveit2_tutorials.
> Fix references to package to moveit2_tutorials

- doc/planning_scene_ros_api/src/planning_scene_ros_api_tutorial.cpp
Added explicit conversion to avoid the build warning mentioned in #122
Fixes #122  (<-- this will close the issue automatically when this PR is merged)
> fix deprecated implicit conversion

- .github/mergify.yml
@henningkayser and I talked recently about trying out mergify for backporting (which is already enabled on ros-planning organization), this PR adds mergify to main branch, then we can use mergify to backport mergify in the other branches 😆. For that can we have backport-galactic and backport-foxy labels for that @henningkayser?
> Add mergify for backporting PRs

- doc/move_group_interface/move_group_interface_tutorial.rst
This fixes a link to the MoveGroupInterface to instead point to the header file in foxy.
> Fix link to MoveGroupInterface

- doc/planning_scene_ros_api/src/planning_scene_ros_api_tutorial.cpp
I've tested this fixing this error on galactic.  It needs to be also tested on rolling:
```
--- stderr: moveit2_tutorials                                                                                             
/home/tyler/code/m2/ws_tutorial/src/moveit2_tutorials/doc/planning_scene_ros_api/src/planning_scene_ros_api_tutorial.cpp: In function ‘int main(int, char**)’:
/home/tyler/code/m2/ws_tutorial/src/moveit2_tutorials/doc/planning_scene_ros_api/src/planning_scene_ros_api_tutorial.cpp:164:77: error: ‘using SharedFuture = class std::shared_future<std::shared_ptr<moveit_msgs::srv::ApplyPlanningScene_Response_<std::allocator<void> > > >’ {aka ‘class std::shared_future<std::shared_ptr<moveit_msgs::srv::ApplyPlanningScene_Response_<std::allocator<void> > > >’} has no member named ‘future’ …
```
> Fix response future type

- .github/workflows/deploy.yml
- README.md
- conf.py
- package.xml
Updated the URL to point to `moveit.picknik.ai`. This should fix the ssl cert issue.
> change base url and cname to moveit.picknik.ai

- .github/workflows/deploy.yml
This is needed so the deploy multiversion works.  I tested this on the foxy branch.
> Fetch all branches

- htmlproofer.sh
We are having flaky 429 errors (too many requests) from Github links, which are irrelevant and seems like a Github issue. This PR will ignore 429 errors.
> Disable 429 errors

- doc/realtime_servo/src/servo_cpp_interface_demo.cpp
based off https://github.com/ros-planning/moveit2_tutorials/pull/109
review / merge that one first
This is an update to reflect the changes in my two Servo PRs in moveit2.
Currently, if you run any of the demos on Rolling with use_intra_process_comms set to true it throws an exception and exits.  Here is an example of the output logs with this setting.
```
2: [component_container_mt-2] [ERROR] [1633289373.749679012] [test_servo_integration_container]: Component constructor threw an exception: intraprocess communication is not allowed with a zero qos history depth value
2: [ERROR] [launch_ros.actions.load_composable_nodes]: Failed to load node 'servo_node' of type 'moveit_servo::ServoNode' in container '/test_servo_integration_container': Component constructor threw an exception: …
```
> Disable use_intra_process_comms for moveit_servo tutorial

- moveit2_tutorials.repos
ros2 branch of mvt will not compile on foxy any more after the last changes, and all the foxy builds of tutorials will fail. We should use the foxy branch of moveit_visual_tools from now on for Foxy builds.
> Use foxy branch for moveit_visual_tools

- doc/quickstart_in_rviz/quickstart_in_rviz_tutorial.rst
I found the "Moving into collision" section in the RViz Quickstart tutorial a little confusing, so I added some instructions to clarify.  Specifically, it took me a minute to figure out that I was supposed to move the start state into collision with itself, not with the goal state or the scene robot.  I also added some instructions for turning on/off visualization elements at the proper time so the user's screen will more closely match the screenshots in the tutorial.
> Add some clarification in the "Moving into collision" section.

- _templates/page.html
This puts back the development version banner to the tutorials website now that it has been refactored to hide all the not-yet-ported pieces in the Examples section.
> :fire: Development branch banner

- README.md
- doc/examples/mobile_base_arm/mobile_base_arm_tutorial.rst
- doc/examples/realtime_servo/realtime_servo_tutorial.rst
- doc/tutorials/quickstart_in_rviz/quickstart_in_rviz_tutorial.rst
Due to the way multiversion deployment works, we have to use relative paths for videos with the raw html feature.  An example of a broken video is in here:
https://moveit.picknik.ai/main/doc/examples/realtime_servo/realtime_servo_tutorial.html#id1
There are probably more clever ways of doing this but I was not able to figure any of them out.
> :fire: Fix embeded video

- conf.py
ROS 1 tutorials were connected to the moveit.ros.org Google Analytics account [here](https://github.com/ros-planning/moveit2_tutorials/pull/208/files#diff-796eab59177eac7e3a920bc2c60dab7dc133e977ebcaab971c80c5147d3a3a18L80)
This restores that, though its not using the fancy tag manager approach but just the built in sphynix-rtd-theme approach.
This should be cherry-picked to foxy and galactic.
> Restore Google Analytics

- doc/examples/bullet_collision_checker/bullet_collision_checker.rst
- doc/examples/chomp_planner/chomp_planner_tutorial.rst
- doc/examples/controller_configuration/controller_configuration_tutorial.rst
- doc/examples/creating_moveit_plugins/plugin_tutorial.rst
- doc/examples/motion_planning_api/motion_planning_api_tutorial.rst
- doc/examples/motion_planning_pipeline/motion_planning_pipeline_tutorial.rst
- doc/examples/move_group_interface/move_group_interface_tutorial.rst
- doc/examples/move_group_python_interface/move_group_python_interface_tutorial.rst
- doc/examples/moveit_cpp/moveitcpp_tutorial.rst
- doc/examples/perception_pipeline/perception_pipeline_tutorial.rst
- doc/examples/pick_place/pick_place_tutorial.rst
- doc/examples/planning_scene/planning_scene_tutorial.rst
- doc/examples/planning_scene_ros_api/planning_scene_ros_api_tutorial.rst
- doc/examples/realtime_servo/realtime_servo_tutorial.rst
- doc/examples/robot_model_and_robot_state/robot_model_and_robot_state_tutorial.rst
- doc/examples/stomp_planner/stomp_planner_tutorial.rst
- doc/examples/subframes/subframes_tutorial.rst
- doc/examples/tests/tests_tutorial.rst
- doc/examples/visualizing_collisions/visualizing_collisions_tutorial.rst
The links in the examples tutorials didn't contain "examples/" prefix. Fixed'em.
> Fix Examples Links

- _templates/page.html
- _templates/versions.html
I think we should call our ``main`` branch "latest" and our ``foxy`` branch "stable / recommended", similar to how [this ReadTheDocs example website](https://sphinx-rtd-theme.readthedocs.io/en/stable/) does it:
As such I have made ours look like this:
I've also turned back on the old CSS that makes alert boxes look nicer:
> Improve wording of different versions, add CSS to warning box

- requirements.txt
Sphinx 4.4.0 (released yesterday) seems broken and causing sphinx-build to fail in CI and local builds. This forces pip to install 4.3.2 instead to fix the builds temporarily.
> Use sphinx 4.3.2 to fix sphinx-builds

- index.rst
With the new tutorials layout, it appears at first glance we have far less content now. To reduce this, I think we should move "Examples" up in the nav right under Tutorials, since that is where the bulk of the content still lives. I think we should order based on relevant to a beginner user:
- Tutorials
- Examples (where all the old tutorials now live)
- Concepts
- How-To-Guides (there is almost nothing here currently)
- API Documentation
- Contributing (this is important to PickNik developers maybe, but not the most important thing for new users)
> Reorder Top Level Navigation

- doc/tutorials/getting_started/getting_started.rst
`sudo rosdep init` must be called before running `rosdep update`. The instructions to install ROS via Debian packages never instructs the user to do this so we must add this command here.
> Add missing rosdep command

- conf.py
- doc/tutorials/getting_started/getting_started.rst
- htmlproofer.sh
Corrected the ROS_DISTRO in conf.py file in the galactic branch from rolling to galactic. 
> Changed rolling to galactic in tutorials

- doc/examples/planning_scene_ros_api/src/planning_scene_ros_api_tutorial.cpp
When I build the tutorials on ros2 rolling I got the following warning:
```
warning: ‘rclcpp::Client<ServiceT>::FutureAndRequestId::operator rclcpp::Client<ServiceT>::SharedFuture() [with ServiceT = moveit_msgs::srv::ApplyPlanningScene; rclcpp::Client<ServiceT>::SharedFuture = std::shared_future<std::shared_ptr<moveit_msgs::srv::ApplyPlanningScene_Response_<std::allocator<void> > > >; typename ServiceT::Response::SharedPtr = std::shared_ptr<moveit_msgs::srv::ApplyPlanningScene_Response_<std::allocator<void> > >]’ is deprecated: FutureAndRequestId: use .future.share() instead of an implicit conversion [-Wdeprecated-declarations]
```
This PR fixes the warning and reverts the changes introduced by #198. It does not seem deprecated in foxy or galactic so I am not sure if this commit should be …
> Revert #198 - Fix future deprecation warning

- doc/examples/controller_configuration/controller_configuration_tutorial.rst
This fixes a broken link to an example controller configuration file. This probably happened because the file's name was updated to use the standard "moveit_controllers.yaml" naming convention.
> Fix broken link to controller config file

- doc/tutorials/quickstart_in_rviz/launch/demo.launch.py
Fix this error due to a recent ROS2 Rolling change:
`stdoutstderr is not a valid standard output config i.e. "screen", "log" or "both"`
> Update launch file to use output="both"

- doc/examples/realtime_servo/src/servo_cpp_interface_demo.cpp
- moveit2_tutorials.repos
Including tf2_ros::Buffer in the PlanningSceneMonitor constructor has been depreciated, fixing leftover references here:
- moveit_visual_tools version 4.1.0 fixed a depreciated constructor, updated the version to be pulled by this package (building with 4.0.0 results in a warning).
- servo demo had a leftover depreciated constructor
> Fix references to depreciated PlanningSceneMonitor constructor

- moveit2_tutorials.repos
If git is not setup with ssh the cloning step will fail.
```
vcs import < moveit2_tutorials/moveit2_tutorials.repos
```
I was following this moveit2 tutorial:
https://moveit.picknik.ai/main/doc/tutorials/getting_started/getting_started.html#create-a-colcon-workspace-and-download-tutorials
> Use https git URL for cloning srdf repo

- doc/tutorials/getting_started/getting_started.rst
It is hard and slow to install all of MoveIt from source in the Getting Started tutorial, so @vatanaksoytezer recommended [in this discussion](https://github.com/ros-planning/moveit2_tutorials/issues/404) we also mention the availability of pre-made Docker files.
> Mention Docker as alternative Getting Started path

- CMakeLists.txt
- doc/tutorials/quickstart_in_rviz/CMakeLists.txt
- doc/tutorials/quickstart_in_rviz/launch/demo.launch.py
- doc/tutorials/quickstart_in_rviz/test/bringup_test.cpp
- doc/tutorials/quickstart_in_rviz/test/bringup_test.test.py
This adds an integration test for the first tutorial presented to new users: [MoveIt Quickstart in RViz](https://moveit.picknik.ai/main/doc/tutorials/quickstart_in_rviz/quickstart_in_rviz_tutorial.html). It checks that the expected nodes and action servers are available.
I think this type of test is great to have, especially on the entry point to MoveIt for most new users. There are quite a few issues this type of test would have helped to catch in the past including [[1](https://github.com/ros-planning/moveit2_tutorials/issues/385), [2](https://github.com/ros-planning/moveit2_tutorials/issues/308), [3](https://github.com/ros-planning/moveit2_tutorials/issues/193), [4](https://github.com/ros-planning/moveit_resources/pull/129)].
You can verify the test passes locally like so:
`colcon test …
> Quickstart tutorial: Add an integration test for the expected nodes

- doc/tutorials/pick_and_place_with_moveit_task_constructor/pick_and_place_with_moveit_task_constructor.rst
- doc/tutorials/pick_and_place_with_moveit_task_constructor/src/main.cpp
Remove an unused property from the MTC tutorial.
There's also separate new issue with the MTC tutorial in which it segfaults on the latest MTC build. Will address that in a separate PR.
> Remove unused hand property from MTC tutorial

- doc/examples/ompl_interface/ompl_interface_tutorial.rst
This should fix https://github.com/ros-planning/moveit2/issues/1321 (the wording confused me).
> Clarify where the motion planning timeout comes from

- doc/tutorials/visualizing_in_rviz/visualizing_in_rviz.rst
- doc/tutorials/your_first_project/your_first_project.rst
Split off from #422 (and thus #404) per @vatanaksoytezer - found and fixed a couple small grammar errors in the tutorials.  
> Fix grammar nits

- doc/examples/pick_place/pick_place_tutorial.rst
This update to the pick and place documentation notes that the pick and place functionality from MoveIt1 is deprecated and that the current method of doing a pick and place operation it to use the MoveIt Task Constructor. 
> Updated the pick and place documentation to note deprecated functionality

- doc/tutorials/pick_and_place_with_moveit_task_constructor/launch/mtc_demo.launch.py
- doc/tutorials/pick_and_place_with_moveit_task_constructor/launch/pick_place_demo.launch.py
- doc/tutorials/pick_and_place_with_moveit_task_constructor/pick_and_place_with_moveit_task_constructor.rst
- doc/tutorials/planning_around_objects/planning_around_objects.rst
- doc/tutorials/quickstart_in_rviz/quickstart_in_rviz_tutorial.rst
- doc/tutorials/visualizing_in_rviz/hello_moveit.cpp
- doc/tutorials/visualizing_in_rviz/visualizing_in_rviz.rst
- doc/tutorials/your_first_project/your_first_project.rst
Reading through the tutorials I had a couple of suggestions
> Tutorial updates

- doc/examples/realtime_servo/realtime_servo_tutorial.rst
Following the addition of [IK plugins for moveit_servo](https://github.com/ros-planning/moveit2/pull/1434), this provides some explanation in the moveit_servo tutorial about how to configure an IK plugin.
> Add explanation about IK plugins for servo

- doc/examples/realtime_servo/realtime_servo_tutorial.rst
It looks like MoveIt Servo does not use the `automatically_declare_parameters_from_overrides` machinery discussed here:
https://github.com/orgs/ros-planning/discussions/1486
This seems to mean that, unlike a `move_group` node, a kinematics plugin loaded by Servo is responsible for declaring any custom parameters it needs to read from the corresponding MoveIt Config's `kinematics.yaml`. 
Maybe this is somehow not the case for configs generated with `MoveItConfigsBuilder`, but it was my experience working on a custom kinematics plugin and modifying the `ur_moveit_config` launch file used by the Universal Robots ROS2 Driver:
https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver/tree/main/ur_moveit_config
I added some text to the "Inverse Kinematics in Servo" section to point at …
> Add detail on custom IK plugin param declaration.

- doc/tutorials/getting_started/getting_started.rst
This will speed up people following the tutorials. I suspect the reason this repo is so huge is the gh_pages branch that contains all the generated API docs now is taking up a ton of space. Until we figure out how to work around that here is a fix for users.
> Shallow clone of tutorials repo

- doc/examples/hybrid_planning/hybrid_planning_tutorial.rst
The classes cannot be found if the plugin import was written like in the tutorial. 
```
[ERROR] [launch_ros.actions.load_composable_nodes]: Failed to load node 'global_planner' of type 'moveit_hybrid_planning::GlobalPlannerComponent' in container '/hybrid_planning_container': Failed to find class with the requested plugin name.
[component_container-5] [ERROR] [1661345481.458624976] [hybrid_planning_container]: Failed to find class with the requested plugin name 'moveit_hybrid_planning::GlobalPlannerComponent' in the loaded library
[component_container-5] [ERROR] [1661345481.470274994] [hybrid_planning_container]: Failed to find class with the requested plugin name 'moveit_hybrid_planning::LocalPlannerComponent' in the loaded library
[ERROR] [launch_ros.actions.load_composable_nodes]: …
```
> Update hybrid_planning_tutorial.rst , launchfile needs to import plugin differently

- doc/tutorials/quickstart_in_rviz/launch/demo.launch.py
- doc/tutorials/quickstart_in_rviz/quickstart_in_rviz_tutorial.rst
Fix several issues with this tutorial:  https://moveit.picknik.ai/humble/doc/tutorials/quickstart_in_rviz/quickstart_in_rviz_tutorial.html
- Launching failed:
`[ERROR] [launch]: Caught exception in launch (see debug for traceback): Caught exception when trying to load file of format [py]: 'robot_description_planning'`
- The `tutorial_arg` argument was not actually used. You can verify this with `grep -r tutorial_arg` on the main branch
Yay for an integration test that caught this!
> Fix launching of the Quickstart tutorial

- moveit2_tutorials.repos
Addresses https://github.com/ros-planning/moveit2_tutorials/issues/511
This change to support chained controllers https://github.com/ros-planning/moveit2/pull/1482 relies on the updated msg format from [ros2_control](https://github.com/ros-controls/ros2_control/commit/94d1e9a9f07c92094992d26c44ac8d9e0a3c9103#diff-ff07c5d9557e55b54b7db28eb20db07c45d7b1f340a784dd1178d704eed2776b).
Otherwise we end up with build errors,
```
ws_moveit2/src/moveit2/moveit_plugins/moveit_ros_control_interface/src/controller_manager_plugin.cpp:471:22: error: ‘struct controller_manager_msgs::msg::ControllerState_<std::allocator<void> >’ has no member named ‘chain_connections’
471 |       if (controller.chain_connections.size() > 1)
|                      ^~~~~~~~~~~~~~~~~
```
Updating ros2_control target version …
> Update ros2_control version to pull in chained controllers information

- doc/tutorials/quickstart_in_rviz/launch/demo.launch.py
The launch file included with the Quickstart in RViz tutorial uses MoveItConfigsUtils with the panda config files in moveit_resources. By default, MoveItConfigsUtils looks for all `_planning.yaml` files, which picks up lerp_planning.yaml and trajopt_planning.yaml. These files produce the following errors (some logs removed for brevity):
```
[ERROR] [1664267382.867870261] [moveit.ros_planning.planning_pipeline]: Exception while loading planner 'lerp_interface/LERPPlanner': According to the loaded plugin descriptions the class lerp_interface/LERPPlanner with base class type planning_interface::PlannerManager does not exist. Declared types are  chomp_interface/CHOMPPlanner ompl_interface/OMPLPlanner pilz_industrial_motion_planner/CommandPlannerAvailable plugins: chomp_interface/CHOMPPlanner, …
```
> Explicitly state which planning pipelines to use in demo launch

- doc/tutorials/getting_started/getting_started.rst
- moveit2_tutorials.repos
In the humble documentation the wrong branch of moveit2 is pulled, therefore the build fails. Updated documentation and moveit2_tutorials.repos to pull branch humble.
> Update Documentation of Humble

- doc/examples/controller_configuration/controller_configuration_tutorial.rst
- doc/examples/creating_moveit_plugins/plugin_tutorial.rst
- doc/examples/dual_arms/dual_arm_panda_moveit_config/config/moveit_controllers.yaml
- doc/examples/dual_arms/dual_arms_tutorial.rst
Update the name of MoveItControllerManager -> Ros2ControlManager, per this MoveIt2 PR:
https://github.com/ros-planning/moveit2_tutorials
> Ros2ControlManager renaming

- doc/tutorials/quickstart_in_rviz/test/bringup_test.cpp
My compiler warned that this function is unused.
> Delete an unused function

- doc/examples/visualizing_collisions/src/visualizing_collisions_tutorial.cpp
- doc/tutorials/getting_started/getting_started.rst
A very small formatting fix.
Before:
After:
> Fix the formatting of Cyclone commands

- doc/examples/move_group_interface/src/move_group_interface_tutorial.cpp
This updates the tutorial to make users aware the existence and role of the MoveGroupInterface::setJointValueTarget boolean return.
Move group currently will allow setJointValueTarget to set a joint target outside of joint limits and MoveGroupInterface::plan will return a success (with a warning of "Joint <> is constrained to be above the maximum bounds. Assuming maximum bounds instead."). This is unexpected behavior by some users and this update to the tutorial will make it more clear where they should check to catch this kind of behavior.
It also makes a small clarification to the xterm usage.
> Draw attention to return value of MoveGroupInterface::setJointValueTarget

- moveit2_tutorials.repos
Here lies a trade-off. In the past, we pinned ros2_control to some version (2.19.0).
First we did it because of the breaking change in ros2_control from Fake to Mock: https://github.com/ros-planning/moveit2_tutorials/commit/215c7711fb568c9492515027c50f06dafa40ae10
Then it got bumped again recently to the "latest version": https://github.com/ros-planning/moveit2_tutorials/commit/502f5e6dca1dab4b42da7df260c140da6de8b668
This was just 4 days ago... yet the latest version of ros2_control on Rolling is not 2.19.0, it is 3.5.0. See [ros index](https://index.ros.org/r/ros2_control/#rolling).
We can keep trying to update this or switch to using ros2_control from the buildfarm's binaries. The second choice is the correct one. The trade-off, though, is that we need to pay attention to breaking …
> Remove ros2_control from repos file on main

- conf.py
Galactic is now a deprecated version of ROS. This makes it deprecated on our website.
> Deprecate galactic

- doc/tutorials/pick_and_place_with_moveit_task_constructor/launch/mtc_demo.launch.py
This PR fixes the following warnings when launching the MTC demo:
```
[ERROR] [1678136118.485318346] [moveit.ros_planning_interface.moveit_cpp]: Failed to initialize planning pipeline 'trajopt'.
```
```
[ERROR] [1678136118.493854644] [moveit.ros_planning_interface.moveit_cpp]: Failed to initialize planning pipeline 'lerp'.
```
These two errors are caused by MoveIt Configs Utils trying to load all files that match the `*_planning.yaml` files available in MoveIt Resources (see #521). The fix for this is to specify the desired planning pipelines (OMPL, CHOMP, and Pilz), similarly to how it is done in the [Quickstart launch](https://github.com/ros-planning/moveit2_tutorials/blob/main/doc/tutorials/quickstart_in_rviz/launch/demo.launch.py).
```
[rviz2-1] [WARN] [1678136119.251836273] …
```
> Fix launch warnings for MTC tutorial

- doc/tutorials/pick_and_place_with_moveit_task_constructor/CMakeLists.txt
These lines were likely just added for debugging purposes.
> Clean up CMakeLists for MTC tutorial

- doc/how_to_guides/isaac_panda/docker-compose.yaml
- doc/how_to_guides/isaac_panda/launch/isaac_moveit.py
This PR fixes passing the users ROS_DOMAIN_ID into the docker container and also sets up Isaac to use the same value.
> Isaac tutorial: pass through ROS_DOMAIN_ID

- doc/tutorials/quickstart_in_rviz/launch/demo.launch.py
- doc/tutorials/quickstart_in_rviz/quickstart_in_rviz_tutorial.rst
Resolves [Issue 568](https://github.com/ros-planning/moveit2_tutorials/issues/586). This PR just finishes removing the rviz_tutorial launch argument  in `humble`, which was removed in `main`, and partially removed in `humble` following backports. This also updates the documentation to specify the correct argument to use in accordance with the [Quickstart In RViz Tutorial](https://moveit.picknik.ai/humble/doc/tutorials/quickstart_in_rviz/quickstart_in_rviz_tutorial.html) so that the initial scene is empty. 
> Pr fix humble quickstart tutorial launch

- doc/tutorials/getting_started/getting_started.rst
Minor changes on the note about bnuild failing when the PC has low memory.
> Extended warning for low memory build

- doc/examples/motion_planning_python_api/motion_planning_python_api_tutorial.rst
- doc/examples/motion_planning_python_api/scripts/motion_planning_python_api_tutorial.py
There are issues with the headings in the tutorial Markdown, they were being given the same precedence as the tutorial title which this fixes.
Somehow the markdown file had inconsistencies with the tutorial scripts. This is likely due to a force push that overwrote changes, I also ensure that the Markdown file aligns with the scripts.
Closes https://github.com/ros-planning/moveit2_tutorials/issues/643
> Fix python motion planning tutorial

- doc/tutorials/pick_and_place_with_moveit_task_constructor/pick_and_place_with_moveit_task_constructor.rst
- doc/tutorials/pick_and_place_with_moveit_task_constructor/src/mtc_node.cpp
Small fix because I had issues with using the sampling-based planner for group hand when I changed it to PILZ or CHOMP.
> Use interpolation planner instead of sampling planner for hand

- doc/examples/kinematics/src/ros_api_tutorial.cpp
- doc/examples/planning_scene/src/planning_scene_tutorial.cpp
- doc/examples/robot_model_and_robot_state/src/robot_model_and_robot_state_tutorial.cpp
- doc/examples/state_display/src/state_display_tutorial.cpp
Minor variable name cleanup to make the naming more consistent.
> Rename variable kinematic_state to robot_state

- .github/workflows/deploy.yml
- Makefile
- build_locally.sh
- conf.py
- doc/api/api.rst
- doc/api/cpp_api/api.rst
- doc/api/python_api/api.rst
- htmlproofer.sh
This pull request adds API documentation for the MoveItPy library. A sample of the documentation when built locally is provided below. Further changes are required to ensure the code in this pull request is compatible with CI tests. At the moment, to build locally you must have built and be able to import the moveit_py library in order for sphinx.ext.autodoc to generate the required documentation.
- Generate and upload artifacts for website branches within a docker container (remove headache of configuring Python package installation)
- Download and collate artifacts in subsequent job, upload final website artifact to be deployed
- Deprecate multiversion-with-api
[Screencast from 09-01-2022 08:37:49 PM.webm](https://user-images.githubusercontent.com/42982057/187999821-764fe047-2a7d-4809-ab …
> moveit_py API documentation

- .github/workflows/deploy.yml
The removed api.rst would fail to build with the multiversion target since the Python libs are not importable. The corresponding api.html is provided with the copied build artifact already.
> Prevent overriding of Python API artifact

- doc/how_to_guides/parallel_planning/src/parallel_planning_main.cpp
When building, I get this output from the parallel planning tutorial:
```--- stderr: moveit2_tutorials                                       
/workspaces/ros2-rolling-ws/src/moveit2_tutorials/doc/how_to_guides/parallel_planning/src/parallel_planning_main.cpp: In member function ‘void parallel_planning_example::Demo::planAndPrint()’:
/workspaces/ros2-rolling-ws/src/moveit2_tutorials/doc/how_to_guides/parallel_planning/src/parallel_planning_main.cpp:246:25: warning: ‘moveit_controller_manager::ExecutionStatus moveit_cpp::MoveItCpp::execute(const RobotTrajectoryPtr&, bool, const std::vector<std::__cxx11::basic_string<char> >&)’ is deprecated: MoveItCpp::execute() no longer requires a blocking parameter [-Wdeprecated-declarations]
246 |     moveit_cpp_->execute(plan_solution.trajectory, true …
```
> Remove deprecated call to moveit_cpp_->execute()

- moveit2_tutorials.repos
moveit now depends on this change: https://github.com/ros-planning/moveit_msgs/commit/e97a788e80ef2789ded11b3b9b54d0f4b164cc08
cutting a release for moveit_msgs but in the mean time fixing the repos file so it is included
> Add moveit_msgs to repos file

- doc/tutorials/getting_started/getting_started.rst
This fixes the formatting of the list of ROS releases you can install before setting up moveit.
New:
Old:
> Bulleted list of ros instasll instructions

- doc/examples/realtime_servo/launch/servo_cpp_interface_demo.launch.py
- doc/examples/realtime_servo/src/servo_cpp_interface_demo.cpp
This PR fixes the `servo_cpp_interface_demo` and also updates it to reflect the use of `moveit_servo` namespace in the ROS parameters
> [Servo] Fix servo_cpp_interface_demo

- .dockerignore
- doc/how_to_guides/isaac_panda/.docker/Dockerfile
- doc/how_to_guides/isaac_panda/docker-compose.yaml
- doc/how_to_guides/isaac_panda/isaac_panda_tutorial.rst
- doc/how_to_guides/isaac_panda/launch/isaac_demo.launch.py
- doc/how_to_guides/isaac_panda/launch/isaac_moveit.py
- package.xml
Co-authored-by: PeterMitrano mitranopeter@gmail.com
This PR is a replacement of #667 and targets the `main` branch.
---
Expands the existing Isaac sim tutorial to enable using pytorch inside the container along side moveit. This work is in support of World MoveIt Day
https://github.com/orgs/ros-planning/projects/6?pane=issue&itemId=24675770
Currently the scope is quite limited, the goal is simply that you can import pytorch and use the GPU from within the demo_isaac container, and that the new environment has (1) some object the robot can push around and (2) working RGB & Depth images
> update isaac demo with pytorch

- doc/how_to_guides/isaac_panda/isaac_panda_tutorial.rst
- doc/how_to_guides/isaac_panda/launch/isaac_moveit.py
Fixes #706. 
This PR adds a check to the Isaac python launch script to make sure a valid `ROS_DOMAIN_ID` is set and if not defaults to a value of 0.
> Default ROS_DOMAIN_ID if not set for Isaac tutorial

- conf.py
- doc/examples/realtime_servo/realtime_servo_tutorial.rst
This PR fixes some dead links since the Servo refactor to main, which highlighted that some of the URLs in the servo tutorial were pointing directly by URL and not using the `:moveit_codedir:` directive.
> Fix servo links in Humble branch

- doc/tutorials/quickstart_in_rviz/test/bringup_test.cpp
- doc/tutorials/quickstart_in_rviz/test/bringup_test.test.py
Note: Requires https://github.com/ros-planning/moveit2_tutorials/pull/734 to be merged in first, then I will clean up this branch
I found an issue where the bringup test was being run twice, with and without a `TimerAction`. This alone made the tests pass, but the segfault persisted at teardown.
However, adding a 1 second delay at the end of the tests made the segfault go away...
Closes https://github.com/ros-planning/moveit2_tutorials/issues/736
> Fix failure in bringup test

- doc/concepts/kinematics.rst
The current phrasing ("it specifies that a collision check between the two bodies is either not required or wanted") is ambiguous. 
I guess the intended meaning was "the collision check is not required or the collision is wanted". I removed the "wanted" part to keep the wording consistent with the next sentence and remove the apparent redundancy.
> Remove ambiguity in kinematics.rst

- doc/examples/jupyter_notebook_prototyping/jupyter_notebook_prototyping_tutorial.rst
- doc/examples/jupyter_notebook_prototyping/launch/jupyter_notebook_prototyping.launch.py
- doc/examples/motion_planning_python_api/launch/motion_planning_python_api_tutorial.launch.py
- doc/examples/move_group_interface/launch/move_group.launch.py
- doc/examples/moveit_cpp/launch/moveit_cpp_tutorial.launch.py
- doc/how_to_guides/chomp_planner/launch/chomp_demo.launch.py
- doc/how_to_guides/isaac_panda/launch/isaac_demo.launch.py
- doc/how_to_guides/parallel_planning/launch/parallel_planning_example.launch.py
- doc/how_to_guides/persistent_scenes_and_states/launch/persistent_scenes_demo.launch.py
- doc/how_to_guides/pick_ik/launch/demo_pick_ik.launch.py
- doc/how_to_guides/using_ompl_constrained_planning/launch/ompl_constrained_planning.launch.py
- doc/tutorials/pick_and_place_with_moveit_task_constructor/launch/mtc_demo.launch.py
- doc/tutorials/quickstart_in_rviz/launch/demo.launch.py
- doc/tutorials/quickstart_in_rviz/launch/panda_demo.launch.py
Fix static_transform_publisher warning:
```
[WARN] [1692255660.769464305] []: Old-style arguments are deprecated; see --help for new-style arguments
```
see: https://docs.ros.org/en/rolling/Tutorials/Intermediate/Tf2/Writing-A-Tf2-Static-Broadcaster-Cpp.html#the-proper-way-to-publish-static-transforms
> Fix static_transform_publisher old-style argments warning

- .vscode/settings.json
- doc/how_to_guides/isaac_panda/launch/isaac_demo.launch.py
In the Isaac tutorial if you try to run the demo.launch MoveIt would crash on startup saying it cant find the Chomp plugin. Because the tutorial does not need chomp I just removed it from the launch file.
Fixes https://github.com/ros-planning/moveit2_tutorials/issues/750
> Remove Chomp from Isaac Tutorial launch file

- doc/tutorials/pick_and_place_with_moveit_task_constructor/pick_and_place_with_moveit_task_constructor.rst
In the "Launch files" section of the "Pick and Place with MoveIt Task Constructor":
1) Link the intended initial launch file.
2) Include a step to install the launch files.
- Re-route a link to an unintended file to the intended file.
- Add a required install step. If this step is not completed, then the launch command the user is directed to run does not work
> Fixup launch details in MTC tutorial

- .github/workflows/deploy.yml
This is the second PR directed at fixing this issue:
- https://github.com/ros-planning/moveit2_tutorials/issues/729
This one synchronizes the deploy from main to humble so it follows the same process.
> Make deploy from humble use the same process as main

- moveit2_tutorials.repos
This change adds pick_ik as a repo needed to build `moveit2_tutorials` from source. Otherwise `rosdep` will pull the precompiled packages for it and its dependencies, including moveit core packages, which may enter in conflict with the source installation.
> add pick_ik to moveit2_tutorials.repos

- moveit2_tutorials.repos
`ros2_kortex` binaries are not yet released for rolling. Hence adding it to the `.repos` file
> Add ros2_kortex to .repos file

- moveit2_tutorials.repos
This removes rosparam_shortcuts from the workspace because it's not used by any of the tutorials anymore.
> Remove unused rosparam_shortcuts from workspace

- .docker/Dockerfile
- .dockerignore
- .github/workflows/docker-images.yml
This PR started out trying to fix the CI job `Build Tutorial Image` so that it supported both `humble` and `rolling` but as we investigated further it did not make sense to build both `humble` and `main` when changes were only made to one branch. A follow up PR will be made to the `humble` branch to only build and update the corresponding image.
This is an attempt to fix the `Build Tutorial Image` step for humble. It's currently failing with the following error.
```
#18 517.2 --- stderr: hello_moveit
#18 517.2 /root/ws_moveit/src/hello_moveit/src/hello_moveit.cpp: In function 'int main(int, char**)':
#18 517.2 /root/ws_moveit/src/hello_moveit/src/hello_moveit.cpp:107:36: error: 'std::tuple_element<1, const std::pair<bool, moveit::planning_interface::MoveGroupInterface::Plan> >::type' {aka …
```
> Change `Build Tutorial Image` CI job to only build main against Rolling

- .docker/Dockerfile
- .dockerignore
- .github/workflows/ci.yaml
- .github/workflows/deploy.yml
- .github/workflows/docker-images.yml
- .github/workflows/format.yml
This is the follow up to #782 so that changes to the `humble` branch only build a Humble docker image.
> Change Build Tutorial Image CI job to only build humble branch against Humble

- doc/tutorials/getting_started/getting_started.rst
Since I cleaned up the history of the git repo to remove the output of the statically generated site, this repo is now much faster to clone. It is generally a better git experience to have a normal clone instead of a shallow one when contributing.
```
time git clone https://github.com/ros-planning/moveit2_tutorials
Cloning into 'moveit2_tutorials'...
remote: Enumerating objects: 7736, done.
remote: Counting objects: 100% (1142/1142), done.
remote: Compressing objects: 100% (688/688), done.
remote: Total 7736 (delta 636), reused 828 (delta 442), pack-reused 6594
Receiving objects: 100% (7736/7736), 91.83 MiB | 11.03 MiB/s, done.
Resolving deltas: 100% (4638/4638), done.
________________________________________________________
Executed in   11.08 secs    fish           external
usr time …
```
> Remove the note about doing a shallow checkout of tutorials

- doc/how_to_guides/isaac_panda/.docker/Dockerfile
- doc/how_to_guides/isaac_panda/.docker/ros_entrypoint.sh
- doc/how_to_guides/isaac_panda/isaac_panda_tutorial.rst
Current Isaac tutorial is broken because the [custom binary images for MoveIt2](https://github.com/moveit/moveit2_packages/issues/6) have stopped being updated. This PR updates the Isaac tutorial docker image to use the [new source build containers](https://github.com/ros-planning/moveit2/pkgs/container/moveit2) @tylerjw recently added :1st_place_medal:.
Tutorial now gets all required ROS packages from the new MoveIt container and topic_based_ros2_control from binary.
> Update Isaac tutorial to use main-humble-tutorial-source docker image

- doc/examples/motion_planning_python_api/config/motion_planning_python_api_tutorial.yaml
- doc/examples/motion_planning_python_api/scripts/motion_planning_python_api_tutorial.py
As outlined [here](https://github.com/ros-planning/moveit2_tutorials/issues/724), users were encountering errors due to the config file in the motion planning tutorial for the Python API.
> moveit_py: fix motion planning tutorial configs

- doc/how_to_guides/pilz_industrial_motion_planner/pilz_industrial_motion_planner.rst
- doc/how_to_guides/pilz_industrial_motion_planner/src/pilz_move_group.cpp
- doc/how_to_guides/pilz_industrial_motion_planner/src/pilz_mtc.cpp
- doc/tutorials/quickstart_in_rviz/launch/demo.launch.py
- doc/tutorials/your_first_project/your_first_project.rst
Along with https://github.com/ros-planning/moveit_resources/pull/190, this PR fixes the Pilz tutorial to work again.
Closes https://github.com/ros-planning/moveit2_tutorials/issues/795
> Update instructions for Pilz tutorial

- doc/examples/planning_with_approximated_constraint_manifolds/planning_with_approximated_constraint_manifolds_tutorial.rst
- doc/how_to_guides/isaac_panda/isaac_panda_tutorial.rst
- doc/tutorials/getting_started/getting_started.rst
- doc/tutorials/quickstart_in_rviz/quickstart_in_rviz_tutorial.rst
https://github.com/ros-planning/moveit2_tutorials/pull/585/ was recently merged but it had a malformed doc link, so this fixes it.
I also found a few more broken URLs that I tacked on to this PR as well.
CI will pass after https://github.com/ros-planning/moveit2/pull/2481 is merged.
> Fix broken URLs in tutorials docs

- .docker/Dockerfile
- doc/tutorials/getting_started/getting_started.rst
- doc/tutorials/quickstart_in_rviz/quickstart_in_rviz_tutorial.rst
We don't have any open [issues with FastDDS](https://github.com/ros-planning/moveit2/issues/1874) anymore, everything is running fine per our knowledge. Let's remove this recommendation.
> Remove recommendation for Cyclone due to FastDDS issues

- doc/tutorials/getting_started/getting_started.rst
Added the branch command to clone the humble branch of the `moveit2_tutorials` repo to make sure there are no compatibility issues with ROS 2 Humble.
Added the `-b humble` flag to line
> 50 | git clone https://github.com/ros-planning/moveit2_tutorials
on the Getting started tutorial.
> Fixed docs: Clone correct moveit2_tutorials branch for Humble

- doc/tutorials/getting_started/getting_started.rst
workspace name was inconsistent with others.
Stumbled upon this while setting up tutorial, cd command refers to directory that does not exist.
changed directory name to allign with others in tutorial.
> fix cd command

- doc/examples/motion_planning_api/launch/motion_planning_api_tutorial.launch.py
- doc/examples/motion_planning_api/src/motion_planning_api_tutorial.cpp
Fixes https://github.com/ros-planning/moveit2_tutorials/issues/823
I changed the launch file for the `motion_planning_api_tutorial` tutorial to accommodate the parameter namespace Moveit2 currently uses for loading plugins. For example, before the kinematic solver was loaded using a parameter called `panda_arm.kinematics_solver` and now it uses `robot_description_kinematics.panda_arm.kinematics_solver` which is the result of using the `MoveItConfigsBuilder`.    
> Fix parameters in motion planning API tutorial

- doc/tutorials/pick_and_place_with_moveit_task_constructor/pick_and_place_with_moveit_task_constructor.rst
The MTC tutorial tells users to run executables which will fail since they need parameters to be passed into the node. Use the launch files while are already available instead.
Run 
```
ros2 launch moveit_task_constructor_demo demo.launch.py
```
and 
```
ros2 launch moveit_task_constructor_demo cartesian.launch.py 
ros2 launch moveit_task_constructor_demo modular.launch.py 
```
Cartesian
https://github.com/ros-planning/moveit2_tutorials/assets/17363793/d575d987-5e1f-45f4-80be-c54b936a2a62
Modular
https://github.com/ros-planning/moveit2_tutorials/assets/17363793/fd2256b6-e2ae-44ab-880b-13f0cd67faf0
> [MTC tutorial] Use launch files instead of running executable 

- doc/tutorials/getting_started/getting_started.rst
https://colcon.readthedocs.io/en/released/reference/executor-arguments.html#:~:text=%2D%2Dparallel%2Dworkers%20NUMBER
While going through the tutorial for MoveIt2 I noticed a minor type in the warning for the compilation step. Note: No formatting was changed, so I am skipping the `clang-format` check.
> Fix minor typo in getting_started.rst

- doc/examples/dual_arms/dual_arms_tutorial.rst
Since #640, these files were removed from the tutorials repo and link is outdated. Since https://github.com/ros-planning/moveit_resources/pull/164, these files were added to moveit_resources. This PR updates the link to point to the new location.
> Update link in dual arms tutorial to point to moveit_resources

- .pre-commit-config.yaml
- doc/examples/controller_configuration/controller_configuration_tutorial.rst
- doc/examples/creating_moveit_plugins/lerp_motion_planner/src/lerp_example.cpp
- doc/examples/hybrid_planning/hybrid_planning_tutorial.rst
- doc/examples/jupyter_notebook_prototyping/jupyter_notebook_prototyping_tutorial.rst
- doc/examples/jupyter_notebook_prototyping/src/moveit_notebook_tutorial.ipynb
- doc/examples/realtime_servo/realtime_servo_tutorial.rst
- doc/examples/time_parameterization/time_parameterization_tutorial.rst
- doc/how_to_guides/controller_teleoperation/controller_teleoperation.rst
- doc/how_to_guides/isaac_panda/.docker/ros_entrypoint.sh
- doc/how_to_guides/isaac_panda/isaac_panda_tutorial.rst
We have some misspelled MoveIt occurrences in the tutorials. https://github.com/ros-planning/moveit/pull/2692 has a nice check that tries to catch these. This PR brings in that check and fixes the misspellings.
Maintain the exception for non-words characters in https://github.com/ros-planning/moveit/pull/2692 to prevent failures due to class names like MoveitCpp.
This PR also augments that check for MoveIt 2 so we [respect the space](https://moveit.ros.org/about/press_kit/).
> Check for and fix misspelled MoveIt

- doc/examples/jupyter_notebook_prototyping/jupyter_notebook_prototyping_tutorial.rst
- doc/examples/jupyter_notebook_prototyping/launch/jupyter_notebook_prototyping.launch.py
- doc/examples/motion_planning_python_api/launch/motion_planning_python_api_tutorial.launch.py
- doc/examples/move_group_interface/launch/move_group.launch.py
- doc/examples/moveit_cpp/launch/moveit_cpp_tutorial.launch.py
- doc/examples/realtime_servo/launch/pose_tracking_tutorial.launch.py
- doc/how_to_guides/chomp_planner/launch/chomp_demo.launch.py
- doc/how_to_guides/isaac_panda/launch/isaac_demo.launch.py
- doc/how_to_guides/moveit_launch_files/moveit_launch_files_tutorial.rst
- doc/how_to_guides/parallel_planning/launch/parallel_planning_example.launch.py
- doc/how_to_guides/persistent_scenes_and_states/launch/persistent_scenes_demo.launch.py
- doc/how_to_guides/pick_ik/launch/demo_pick_ik.launch.py
- doc/how_to_guides/using_ompl_constrained_planning/launch/ompl_constrained_planning.launch.py
- doc/tutorials/pick_and_place_with_moveit_task_constructor/launch/mtc_demo.launch.py
- doc/tutorials/quickstart_in_rviz/launch/demo.launch.py
Related to https://github.com/ros-planning/moveit2/pull/2620
> Update ros2_control_node initialization

- CMakeLists.txt
Currently, the collision_environments subdirectory (which contains the collision scene example) isn't being built. The collision scene example is used in the [CHOMP tutorial](https://moveit.picknik.ai/main/doc/how_to_guides/chomp_planner/chomp_planner_tutorial.html), which asks the user to run: `ros2 run moveit2_tutorials collision_scene_example`.
Current behaviour:
```bash
$ ros2 run moveit2_tutorials collision_scene_example         
No executable found
```
Expected behaviour after fix:
```bash
$ ros2 run moveit2_tutorials collision_scene_example         
```
The above command should not produce the `No executable found` output. Instead, you should see some boxes in the collision environment. Here's what it looks like when running through the tutorial:
> Build collision scene example

- .github/workflows/deploy.yml
CI seems to be failing because we are using an old version of ruby that our dependencies for htmlprofer no longer support. Locally, on Ubuntu 22.04, the version of ruby I have that works is 3 so I am trying to set the version in CI to 3 to see if it fixes it.
> Upgrade the version of ruby used in CI

- .github/workflows/deploy.yml
- conf.py
- doc/examples/planning_with_approximated_constraint_manifolds/planning_with_approximated_constraint_manifolds_tutorial.rst
- doc/examples/stomp_planner/stomp_planner_tutorial.rst
- doc/examples/visualizing_collisions/src/visualizing_collisions_tutorial.cpp
- doc/how_to_guides/chomp_planner/chomp_planner_tutorial.rst
- requirements.txt
Need this update to get CI passing for https://github.com/ros-planning/moveit2_tutorials/pull/854
> Update requirements.txt for humble branch

- conf.py
- requirements.txt
Currently, the `htmlproofer` and `upload_site_artifacts` CI jobs are failing on main due to 
```
Sphinx version error:
The sphinxcontrib.applehelp extension used by this project needs at least Sphinx v5.0; it therefore cannot be built with this version.
```
> Update sphinx version for CI to pass on main

- .github/workflows/deploy.yml
- conf.py
I think @Abishalini was on the right track with https://github.com/ros-planning/moveit2_tutorials/pull/857, we may just need to explicitly exclude the core package under moveit.
> Ignore MoveIt and MoveIt Core Packages from docs Imports

- .github/workflows/deploy.yml
This furthers the hack we employ to get Python bindings docs working with Sphinx multiversion...
> Manually copy entire Python bindings docs folder instead of just `api.html`

- .github/workflows/deploy.yml
- conf.py
This PR backports (most of) https://github.com/ros-planning/moveit2_tutorials/pull/859 and https://github.com/ros-planning/moveit2_tutorials/pull/860 to fix humble docs build in CI.
> Backport docs CI fixes from main

- doc/examples/moveit_cpp/launch/moveit_cpp_tutorial.launch.py
Was debugging something and had a very minor cleanup here.
> Use os.path.join for all paths in MoveItCpp tutorial launch file

- doc/how_to_guides/isaac_panda/launch/isaac_moveit.py
- doc/how_to_guides/isaac_panda/launch/python.sh
In addition, the header of the Isaac Sim launch script has been updated to indicate that it has been licensed (by NVIDIA) under BSD-3.
Isaac Sim 4.0 will be released soon, and these changes are required for compatibility (while also maintaining compatibility with older versions).
As a bit of housekeeping, I've also received the necessary approvals to release this file under BSD-3.  Marq had copied the original version of the file from Isaac Sim, which is licensed under the NVIDIA Omniverse license, hence the "any use [...] without an express license agreement from NVIDIA CORPORATION is strictly prohibited" language in the old header.
> Update isaac_panda example for compatibility with Isaac Sim 4.0

- .github/upstream.repos
- moveit2_tutorials.repos
In Ubuntu 24.04, Gazebo classic is no longer supported or available from binaries. Due to the `ros2_kortex` repo still using this as a dependency, CI has been failing.
See: https://github.com/Kinovarobotics/ros2_kortex/issues/217 and https://github.com/Kinovarobotics/ros2_kortex/pull/228
So, to have this work, we (and all consumers of this package on Jazzy onwards) have to get around this.
> Use fork of `ros2_kortex` that does not depend on Gazebo classic

- .github/workflows/deploy.yml
- doc/how_to_contribute/how_to_contribute_to_site.rst
- htmlproofer.sh
Fix this error:
```
error: externally-managed-environment
× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
python3-xyz, where xyz is the package you are trying to
install.
If you wish to install a non-Debian-packaged Python package,
create a virtual environment using python3 -m venv path/to/venv.
Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
sure you have python3-full installed.
If you wish to install a non-Debian packaged Python application,
it may be easiest to use pipx install xyz, which will manage a
virtual environment for you. Make sure you have pipx installed.
See /usr/share/doc/python3.12/README.venv for more information.
```
This should make CI pass the "Install Python Dependencies" step.
> Use venv in CI

- build_locally.sh
While I was testing @sea-bass's fixes, I noticed the build locally script doesn't work. Looks like I missed a stray `pip install --user` in #916 .
> Fix stray pip user install

- doc/examples/setup_assistant/setup_assistant_tutorial.rst
In the example section, after building our "own" robot, we need to launch the `demo.launch.py`. Here, the wrong package to launch from is set (already builtin in tutorial source, `moveit_resouces`) to the `moveit_resouces_panda_moveit_config` instead of built `panda_moveit_config`.
> Fix wrong launch package in Setup Assistant tutorial

- .gitignore
- doc/examples/hybrid_planning/hybrid_planning_tutorial.rst
- doc/how_to_guides/how_to_setup_docker_containers_in_ubuntu.rst
- htmlproofer.sh
- index.rst
- requirements.txt
This PR makes an attempt at "fixing" the docs build.
I had to modify the `doxylink` repo (see https://github.com/sphinx-contrib/doxylink/pull/59) since there was an exception without this, and also removed/replaced some old links to make htmlproofer happy.
While the exception was fixed with my PR above, there are still some more build warnings, so I had to remove the `-W` flag from the `sphinx-build` call in `htmlproofer.sh`.
I figured it would be better if the docs actually built and then someone else can try fix the warnings (or change the whole docs build system, which is probably due at this point)
> Fix docs build

- .docker/Dockerfile
There have been issues building the tutorials image because now some of the packages (namely Robotiq and ros2_kortex) depend on Gazebo being installed.
This will work for Jazzy/Rolling, but I think there need to be args introduced to make this work on other distros (or even changing `gz` for `ignition`)
So you will then need to pass in this `GZ_VERSION` arg in the `moveit2` CI job here: https://github.com/moveit/moveit2/blob/1d93035fc4fbc2831916bce26d7b03e15b8a86d5/.github/workflows/tutorial_docker.yaml#L19
NOTE: You should see the effects of this in the post-merge action for this PR. I've also dispatched the workflow so you can see it on this branch: https://github.com/moveit/moveit2_tutorials/actions/runs/10207096230
(all previous failing runs can be found here: …
> Install Gazebo as part of Tutorials image build

- .github/workflows/deploy.yml
A recent PR (#900) had a nonexistent version of the `upload-pages-artifact` action.
Can we re-enable that the docs CI be required?
> Fix `upload-pages-artifact` version in docs CI

- doc/how_to_guides/persistent_scenes_and_states/persistent_scenes_and_states.rst
Broken link highlighting in Warehouse - Persistent Scenes and States page is fixed.
> Fixed link typo in Warehouse - Persistent Scenes and States page

- doc/tutorials/getting_started/getting_started.rst
Modified the cloning instructions to specify a branch explicitly. This change aims to prevent common pitfalls encountered by users related to missing or incompatible packages when using older ROS distributions. By directing users to clone a specific branch, we ensure that they start with a setup that is compatible with their environment, thus reducing initial setup errors and improving the onboarding experience.
> Add branch to `git clone` command in Getting Started docs

- index.rst
This commit removes a stray image link (https://moveit.ros.org/assets/images/roadmap.png) that was found in the documentation. The link was not relevant to the content.
> Fix image link in documentation

- doc/tutorials/getting_started/getting_started.rst
Added code to automatically initialize and update all submodules recursively. This change addresses build errors related to un-initialized submodules, specifically issues with the `pybind11` submodule. The script checks each directory for the presence of `.gitmodules` and, if found, performs the necessary submodule updates. This ensures all dependencies are correctly set up before build, improving the reliability of our build process and reducing setup errors for new users.
> Added code to update submodules during installation

- .github/upstream.repos
The `gz_ros2_control` repo updated their default branch recently. This should fix builds.
It's the same change as https://github.com/moveit/moveit2_tutorials/pull/955, but for some reason we need this in 2 places.
> Update gz_ros2_control branch name in upstream.repos

- .pre-commit-config.yaml
- doc/examples/jupyter_notebook_prototyping/launch/jupyter_notebook_prototyping.launch.py
- doc/examples/motion_planning_pipeline/launch/motion_planning_pipeline_tutorial.launch.py
- doc/examples/motion_planning_python_api/launch/motion_planning_python_api_tutorial.launch.py
- doc/how_to_guides/benchmarking/launch/run_benchmarks.launch.py
- doc/how_to_guides/parallel_planning/launch/parallel_planning_example.launch.py
updated psf/black and  pre-commit-hooks to last version.
cosmetic correction of the code to pass the test
> Cosmetic code fix

- doc/examples/moveit_task_constructor/moveit_task_constructor_tutorial.rst
- Updates the setup and build instructions for the MoveIt Task Constructor from ROS1 to ROS2. The changes include replacing the ROS1 workspace tools and build system with their ROS2 equivalents.
- Updates launch commands for demos since individual launch files were replaced with common run.launch.py in the moveit/moveit_task_constructor repo.
> Humble: Update MoveIt Task Constructor

- .github/workflows/ci.yaml
Since version 4, `actions/cache` supports the setting `save-always`.
> CI: Use actions/cache

- doc/examples/ikfast/ikfast_tutorial.rst
Closes https://github.com/moveit/moveit2_tutorials/issues/27
> Update the IKFast tutorial for ROS2

- doc/tutorials/tutorials.rst
I committed changes in Markdown format, not RST format. Oops.
> Fix formatting in tutorials index page URL

- doc/examples/realtime_servo/config/panda_simulated_config.yaml
- doc/examples/realtime_servo/launch/pose_tracking_tutorial.launch.py
- doc/examples/realtime_servo/realtime_servo_tutorial.rst
- doc/examples/realtime_servo/src/pose_tracking_tutorial.cpp
The Servo pose tracking tutorial was not working as it had likely gone out of date with some other changes.
Also, the way the command switching service was called wasn't properly waiting for the future to complete, which caused me problems. It still doesn't work reliably on FastDDS, but if you switch RMW to CycloneDDS it does.
> Fix Servo pose tracking tutorial

- .github/upstream.repos
- moveit2_tutorials.repos
Now that `gz_ros2_control` is available from binaries on Iron onwards, we can remove this source build.
> Install `gz_ros2_control` from binaries

- doc/concepts/planning_scene_monitor.rst
Address user confusion manifested, e.g. in https://github.com/moveit/moveit2_tutorials/issues/982 and https://github.com/moveit/moveit2/issues/1042.
> Improve PSM documentation

- doc/examples/move_group_interface/src/move_group_interface_tutorial.cpp
- doc/how_to_guides/kinematics_cost_function/src/kinematics_cost_function_tutorial.cpp
Since https://github.com/moveit/moveit2/pull/2916, the `JumpThreshold` in cartesian interpolator was removed and/or replaced with a `CartesianPrecision` struct.
This PR brings things up to date, thereby removing deprecation warnings when compiling.
> Remove/replace deprecated use of JumpThreshold

- .docker/docker-compose.yml
- README.md
- doc/how_to_guides/how_to_setup_docker_containers_in_ubuntu.rst
This PR updates the Docker images used in the tutorials to the new `moveit` Docker Hub organization.
It also updates docs associated with this change, plus how to build documentation locally with virtual environments (needed for Ubuntu 24.04, introduced in #916)
I also tested all the combinations for Humble, Jazzy, and Rolling, and the `demo.launch.py` actually work in all 3 cases! Magical.
Closes https://github.com/moveit/moveit2_tutorials/issues/936
> Update tutorial Docker image names and documentation

- doc/tutorials/getting_started/getting_started.rst
> Iron is dead, long live Jazzy

- doc/how_to_guides/pick_ik/pick_ik_tutorial.rst
- moveit2_tutorials.repos
- package.xml
If people want to use pick_ik, it can still be installed optionally. But it's a bit wasteful to have it be built all the time.
> Remove pick_ik as a dependency

- .github/upstream.repos
- moveit2_tutorials.repos
Seems like `ros-rolling-gz-ros2-control` was removed in the latest Rolling 2025-01-02 sync for some reason. So adding this for now.
https://discourse.ros.org/t/new-packages-for-ros-2-rolling-ridley-2025-01-02/41376/2
> Re-add `gz_ros2_control` source build

- .docker/Dockerfile
Same as https://github.com/moveit/moveit2/pull/3196, but for this repo.
This fix will manifest itself in the "Update Tutorial Images" job succeeding -- here is a manually triggered run on this branch: https://github.com/moveit/moveit2_tutorials/actions/runs/12607223364/job/35138346081
> Use Gazebo Ionic in tutorial images

- .github/upstream.repos
- moveit2_tutorials.repos
Now that https://github.com/Kinovarobotics/ros2_kortex/pull/228 was merged, we can switch back to Kinova's official repo 🎉 
Tested on `ros2 launch moveit2_tutorials demo.launch.py` and it worked for me.
> Switch ros2_kortex to Kinova main branch

- requirements.txt
As described in https://github.com/sphinx-contrib/doxylink/pull/59#issuecomment-2604811415, we should be able to switch to the upstream version of `doxylink` again... thus fully removing a dependency on my personal forks.
> Use latest version of doxylink

- doc/how_to_guides/isaac_panda/isaac_panda_tutorial.rst
- doc/how_to_guides/isaac_panda/launch/isaac_moveit.py
- doc/how_to_guides/isaac_panda/launch/python.sh
With the upcoming release of Isaac Sim 4.5, this PR introduces updates to ensure the [Isaac Panda tutorial](https://moveit.picknik.ai/main/doc/how_to_guides/isaac_panda/isaac_panda_tutorial.html) remains current while maintaining backward compatibility with older versions of Isaac Sim.
Summary of Changes:
- Updated logic to detect Isaac Sim 4.5 in its new installation path.
- Adjusted import statements to accommodate renamed extensions and python modules introduced in Isaac Sim 4.5.
> Update Isaac Panda tutorial to be compatible with Isaac Sim 4.5 and below

- doc/how_to_guides/trajectory_cache/trajectory_cache_tutorial.rst
I accidentally made a copy-paste typo at the bottom...
Sorry for the noise. @sea-bass
> Fix Typo in Trajectory Cache How-To-Guide

- doc/examples/jupyter_notebook_prototyping/jupyter_notebook_prototyping_tutorial.rst
- doc/examples/jupyter_notebook_prototyping/launch/jupyter_notebook_prototyping.launch.py
- doc/examples/motion_planning_python_api/launch/motion_planning_python_api_tutorial.launch.py
- doc/examples/move_group_interface/launch/move_group.launch.py
- doc/examples/moveit_cpp/launch/moveit_cpp_tutorial.launch.py
- doc/examples/perception_pipeline/launch/perception_pipeline_demo.launch.py
- doc/examples/realtime_servo/launch/pose_tracking_tutorial.launch.py
- doc/how_to_guides/chomp_planner/launch/chomp_demo.launch.py
- doc/how_to_guides/isaac_panda/launch/isaac_demo.launch.py
- doc/how_to_guides/moveit_launch_files/moveit_launch_files_tutorial.rst
- doc/how_to_guides/parallel_planning/launch/parallel_planning_example.launch.py
- doc/how_to_guides/persistent_scenes_and_states/launch/persistent_scenes_demo.launch.py
- doc/how_to_guides/pick_ik/launch/demo_pick_ik.launch.py
- doc/how_to_guides/pilz_industrial_motion_planner/launch/pilz_moveit.launch.py
- doc/how_to_guides/trajectory_cache/launch/trajectory_cache_move_group.launch.py
- doc/how_to_guides/using_ompl_constrained_planning/launch/ompl_constrained_planning.launch.py
- doc/tutorials/pick_and_place_with_moveit_task_constructor/launch/mtc_demo.launch.py
- doc/tutorials/quickstart_in_rviz/launch/demo.launch.py
Address https://github.com/moveit/moveit2_tutorials/issues/991 where two nodes are launched with same name `rviz2`. The fix is to remove node name attribute when launching `rviz2`.
> Fix two nodes launched with same name of /rivz2

- doc/examples/perception_pipeline/perception_pipeline_tutorial.rst
Just a small change to make the padding parameters more understandable for users. Closes the issue https://github.com/moveit/moveit2/issues/3285
> Added verbose description for padding parameters

- doc/tutorials/pick_and_place_with_moveit_task_constructor/pick_and_place_with_moveit_task_constructor.rst
I use Ubuntu 22.04 and ros2 humble to run the tutorial. When I clone moveit_task_constructor and build, I face many problem because my moveit is humble version. Therefore I look up the tutorial and find this problem.
change branch from  ``ros2`` to ``$ROS_DISTRO``
> Add note about older branches in pick_and_place_with_moveit_task_constructor.rst

- conf.py
This was causing build errors on a recent PR, and also who cares about this?
Error:
```
Warning, treated as error:
The analytics_id option is deprecated, use the sphinxcontrib-googleanalytics extension instead.
```
I feel like instead of figuring this out or pinning back the Sphinx version, it's best to reMoveIt!
> Remove Google Analytics ID

- doc/examples/moveit_cpp/config/moveit_cpp.yaml
It took me way too long to figure out why `moveit_cpp` was using the CHOMP planning pipeline. It's because `ompl` pipeline wasn't configured here, so MoveIt defaults to the first planning pipeline in the list.
(I've only tested this on Humble, hopefully it hasn't changed since then.)
> Rolling: Add OMPL config to moveit_cpp.yaml

- .github/upstream.repos
- moveit2_tutorials.repos
Rolling is back in order for now... no need to source build `picknik_controllers`.
> Use `picknik_controllers` binaries again

- package.xml
The package got removed upstream in https://github.com/ros-controls/ros2_controllers/pull/1652. Find_packageing this on Kilted or Rolling will lead to errors from the next sync on.
> Remove gripper_controllers dependency
