.travis.yml
Trying to get Travis to add CNAME for custom domain. Should fix CI issues.
=> fix travis for custom domain

htmlproofer.sh
=> Pr fix htmlproofer to work in ROS2

.github/workflows/sphinx-make-page.yml
=> add github action

README.md
@bostoncleek let's avoid saying stuff in open source is "not ready for contributions", we pretty much always want help and comments like that quickly get outdated.
=> Request help with tutorial porting, don't turn people away

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, .github/config.yml
Update things in .github folder for ROS2/MoveIt2
=> Update .github folder

doc/getting_started/getting_started.rst
Sorry I had some issues with #55 so I made a new PR
=> Getting Started port to moveit2

README.md, doc/getting_started/getting_started.rst
- Fix CI badges
- Update information on CI
- Remove unused rosdoc documentation
=> Fix CI badges and cleanup rosdoc documentation

README.md
Clarify what the section is about
=> Clarify README section for porting

doc/getting_started/getting_started.rst
Updates the installation instructions to point website and make the instructions distro-independent.
=> Update installation instructions, and minor claenup

.github/workflows/ci_main.yml, doc/getting_started/getting_started.rst, index.rst
Cleaning up the instructions for installing Foxy to make them simpler.
In support of:
* https://github.com/ros-planning/moveit2/issues/716
=> Cleanup getting started for foxy

doc/getting_started/getting_started.rst
Reference: https://answers.ros.org/question/359586/cannot-figure-out-whats-going-on-with-python3-rosdep2/
=> Fix instructions for installing rosdep

doc/planning_scene_ros_api/launch/planning_scene_ros_api_tutorial.launch.py, doc/planning_scene_ros_api/planning_scene_ros_api_tutorial.rst, doc/planning_scene_ros_api/src/planning_scene_ros_api_tutorial.cpp
This also needs to be done for the main branch too.
=> Update planning_scene_ros_api_tutorial to use rviz prompt

doc/getting_started/getting_started.rst
The current link could be more specific.  This should help avoid confusion as to what we mean.
=> Change link to install Foxy to Debian Instructions

_themes/sphinx_rtd_theme/version_dropdown.html
Removing Kinetic from the dropdown. This will need to be done for Melodic & Noetic versions as well.
=> Remove Kinetic from Dropdown

.github/workflows/ci_main.yml
=> Do not run Rolling CI on this Galactic branch

doc/moveit_cpp/src/moveit_cpp_tutorial.cpp
Closes https://github.com/ros-planning/moveit2_tutorials/issues/168
=> Fix branch in link to panda_arm.xacro

.github/config.yml, README.md, _themes/sphinx_rtd_theme/moveit1_warning.html, doc/move_group_interface/move_group_interface_tutorial.rst, doc/moveit_cpp/moveitcpp_tutorial.rst, doc/planning_scene_ros_api/planning_scene_ros_api_tutorial.rst, doc/urdf_srdf/urdf_srdf_tutorial.rst, index.rst
Closes: #164, #170
Changes: 
- Misc docs updates
- Some clarifications and notes
- Change MoveIt2 to MoveIt 2
=> Misc fixes to tutorials

moveit2_tutorials.repos
Reverts ros-planning/moveit2_tutorials#189
We needed to do a rosdep update :(
unlucky timing.
=> Revert "graph fix"

build_locally.sh, conf.py
This makes the build_locally.sh script match what is in the htmlproofer script.
=> Fix installing of dependencies in build_locally.sh script

_templates/versions.html
Added hard-coded links to ROS1 versions of MoveIt
=> hard code ros1 versions into selector

_templates/versions.html
Fix Hardcodded URLs to version sidebar to access ROS1
=> fix ros1 urls

conf.py
=> Fix extra slashes in github urls

.github/workflows/deploy.yml
This adds deploying from main in the action in foxy to match what is in main.
=> Add main to deploy action

doc/realtime_servo/src/servo_cpp_interface_demo.cpp, moveit2_tutorials.repos
The [update](https://github.com/ros-planning/moveit2/pull/799) to servo parameters changes the function signature of makeServoParameters. This PR is to update the tutorials accordingly once the aforementioned PR is merged.
=> Update servo tutorial for MoveIt servo parameters update

doc/realtime_servo/src/servo_keyboard_input.cpp
This matches the change in motion speed in this PR:  https://github.com/ros-planning/moveit2/pull/886
They should be merged at the same time.
=> Set the keyboard Servo speed to 1.0, not 0.2

README.md
Change foxy to rolling in README
=> Change foxy to rolling in README

doc/how_to_contribute/how_to_contribute_to_site.rst
=> Add a note about rebuilding the website automatically

Makefile, README.md, build_locally.sh
See README.md changes below to understand :-)
=> Improve build_locally script

doc/examples/realtime_servo/realtime_servo_tutorial.rst, package.xml
Add some hints for questions we get over and over again. Also for some "active learning"  ;)
=> Add hints for Servo debugging

doc/how_to_contribute/how_to_write_how_to_guides.rst
Minor language and formatting changes in How to Write a MoveIt How-To Guide
=> Fixes for How To Write How To Guides

doc/examples/controller_configuration/controller_configuration_tutorial.rst
Update the low_level_controllers tutorial for ROS2
This isn't a complete rewrite. My knowledge is a little fuzzy on some sections that are marked with TODO. But, it's a lot better than what we had before.
Would appreciate a review from @schornakj or @JafarAbdi  or @davetcoleman or @MarqRazz  since you guys probably understand the ros2_control interface best.
=> Update low_level_controllers for ROS2

doc/how_to_contribute/how_to_write_tutorials.rst
Minor language and formatting changes in tutorial for writing moveit tutorials
=> Fixes for tutorial on how to write tutorials

doc/concepts/how_to_guide.rst
Minor spelling, grammar, and re-wording changes to the Concepts: How-To Guide. 
=> Fixes for Concepts: How-To Guide

doc/how_to_contribute/how_to_contribute_to_site.rst
- Fix typo.
- Update requirements.
- Formatting.
=> Fixes for "How to Contribute to This Site"

Makefile
This will make the galactic branch of this website the default landing page.
=> :memo: Make Galactic branch the default

doc/concepts/how_to_guide.rst
Correct a couple typos I noticed
=> Typo Fixes

doc/how_to_guides/how_to_generate_api_doxygen_locally.rst, doc/how_to_guides/how_to_guides.rst
Instructions to build API Doxygen reference locally. Depends on ros-planning/moveit2#992.
=> Generate API referene locally

doc/how_to_guides/how_to_generate_api_doxygen_locally.rst
Extends documentation for ros-planning/moveit2#1006.
=> Update documentation for path specification.

Makefile, theme.css
=> add api theme

README.md
=> removed dir structure ( #290 )

doc/examples/move_group_interface/launch/move_group.launch.py, doc/examples/move_group_interface/launch/move_group_interface_tutorial.launch.py, doc/examples/moveit_cpp/config/moveit_cpp.yaml, doc/examples/moveit_cpp/launch/moveit_cpp_tutorial.launch.py, doc/examples/persistent_scenes_and_states/move_group.launch.py, doc/examples/planning_scene/launch/planning_scene_tutorial.launch.py, doc/examples/realtime_servo/launch/servo_cpp_interface_demo.launch.py, doc/examples/robot_model_and_robot_state/launch/robot_model_and_robot_state_tutorial.launch.py, moveit2_tutorials.repos, package.xml
Based on https://github.com/ros-planning/moveit2/pull/591
=> Use moveit configs utils packages

moveit2_tutorials.repos
moveit_resources works on the foxy version.  Also, the branch ros2 of moveit_resources no longer works on foxy.
=> Update repos file on foxy

.pre-commit-config.yaml, doc/examples/ompl_constrained_planning/scripts/extra_examples.py, doc/examples/ompl_constrained_planning/scripts/ompl_constrained_planning_tutorial.py
Update black as mentioned in https://github.com/psf/black/issues/2964
=> Update black version

doc/examples/controller_configuration/controller_configuration_tutorial.rst, doc/examples/move_group_interface/launch/move_group.launch.py, doc/tutorials/getting_started/getting_started.rst, doc/tutorials/quickstart_in_rviz/launch/demo.launch.py, moveit2_tutorials.repos, package.xml
Still need to update instructions for 22.04 and Rolling.
=> Fix htmlproofer and Rolling / Jammy CI

doc/examples/controller_configuration/controller_configuration_tutorial.rst, doc/examples/move_group_interface/launch/move_group.launch.py, doc/examples/moveit_cpp/launch/moveit_cpp_tutorial.launch.py, doc/examples/persistent_scenes_and_states/move_group.launch.py, doc/examples/realtime_servo/launch/servo_cpp_interface_demo.launch.py, doc/tutorials/quickstart_in_rviz/launch/demo.launch.py
Goes with https://github.com/ros-planning/moveit_resources/pull/127 (although some of the links were broken anyway)
CC: @AndyZe 
=> Update panda controller filenames

moveit2_tutorials.repos
=> Remove a bunch of repos

.pre-commit-config.yaml, doc/examples/ompl_constrained_planning/scripts/extra_examples.py, doc/examples/ompl_constrained_planning/scripts/ompl_constrained_planning_tutorial.py
Should fix the error in formatting CI - see https://github.com/ros-planning/moveit2_tutorials/pull/344
=> [galactic] Update black version

doc/tutorials/getting_started/getting_started.rst
Fixes https://github.com/ros-planning/moveit2/issues/1192
=> Add branch info to Galactic build

.github/upstream.repos, .github/workflows/ci.yaml, .github/workflows/format.yml, .pre-commit-config.yaml, doc/examples/move_group_interface/src/move_group_interface_tutorial.cpp, doc/tutorials/getting_started/getting_started.rst, moveit2_tutorials.repos, package.xml
Signed-off-by: Tyler Weaver <tylerjw@gmail.com>
This fixes up the main branch so it builds on Jammy
=> Fixup main branch

doc/examples/mobile_base_arm/mobile_base_arm_tutorial.rst
some mentioned ~/ws_moveit2/ and some ~/ws_moveit/ in the same page
=> fix file directory consistency

doc/examples/mobile_base_arm/mobile_base_arm_tutorial.rst
=> fix inconsistent directories

doc/examples/move_group_interface/launch/move_group.launch.py, doc/examples/moveit_cpp/launch/moveit_cpp_tutorial.launch.py, doc/examples/persistent_scenes_and_states/move_group.launch.py, doc/examples/realtime_servo/launch/servo_cpp_interface_demo.launch.py, doc/tutorials/pick_and_place_with_moveit_task_constructor/launch/mtc_demo.launch.py
=> Update launch file to use output="both"

.github/ISSUE_TEMPLATE.md, .github/mergify.yml, .github/workflows/deploy.yml, conf.py
This adds conf settings for the new humble branch.
=> Enable Humble Tutorial

Makefile
=> Add humble API

doc/tutorials/tutorials.rst
Adapted from the marketing team at Tensorflow: https://www.tensorflow.org/learn
=> Make nicer intro sentence

doc/examples/moveit_task_constructor/moveit_task_constructor_tutorial.rst
Updated the commands needed to install and run the MoveIt Task Constructor demos.
=> Port MoveIt Task Constructor example to ROS 2

doc/examples/mobile_base_arm/mobile_base_arm_tutorial.rst, doc/how_to_contribute/how_to_contribute_to_site.rst, doc/tutorials/getting_started/getting_started.rst, doc/tutorials/pick_and_place_with_moveit_task_constructor/pick_and_place_with_moveit_task_constructor.rst, doc/tutorials/visualizing_in_rviz/visualizing_in_rviz.rst, doc/tutorials/your_first_project/your_first_project.rst
```
grep -rl '~/ws_moveit2' ./ | xargs sed -i 's/ws_moveit2/ws_moveit/g'
```
To conform to docker container directory naming, observations from testing in #404
=> Bulk rename ws_moveit2 --> ws_moveit 

.github/upstream.repos, moveit2_tutorials.repos
This seems to hopefully fix build issues we are having after removing boost.
Fixes #449.
=> Add mvt to repos

doc/how_to_guides/how_to_write_doxygen.rst
Changed the title of the page I added in #423  (from `-----...` to `====...`) so it would be linked to properly.
=> Fixed error in tutorial

.docker/Dockerfile, .github/workflows/docker-base.yml, .github/workflows/docker-images.yml, .github/workflows/docker.yml
=> Docker debug cleanup

doc/examples/dual_arms/dual_arm_panda_moveit_config/config/panda.ros2_control.xacro, doc/examples/dual_arms/dual_arm_panda_moveit_config/config/panda_hand.ros2_control.xacro, moveit2_tutorials.repos
Signed-off-by: Tyler Weaver <tylerjw@gmail.com>
This is a continuation of fixes for tutorials that we have also made in moveit2 for a breaking change in ros2_control.
We should have releases very soon so we can remove these from the repos file soon.
=> Rename fake_components to mock_components

index.rst
Making sure its easy to click through to PickNik ;-)
=> Tweak attribution from corporate sponsorship on homepage

doc/examples/creating_moveit_plugins/lerp_motion_planner/src/lerp_example.cpp, doc/examples/motion_planning_pipeline/src/motion_planning_pipeline_tutorial.cpp, doc/examples/trajopt_planner/src/trajopt_example.cpp, doc/tutorials/pick_and_place_with_moveit_task_constructor/pick_and_place_with_moveit_task_constructor.rst, doc/tutorials/pick_and_place_with_moveit_task_constructor/src/main.cpp, doc/tutorials/pick_and_place_with_moveit_task_constructor/src/minimal.cpp, doc/tutorials/planning_around_objects/hello_moveit.cpp, doc/tutorials/visualizing_in_rviz/hello_moveit.cpp, doc/tutorials/visualizing_in_rviz/visualizing_in_rviz.rst, doc/tutorials/your_first_project/hello_moveit.cpp, doc/tutorials/your_first_project/your_first_project.rst
In going through the MoveIt2 Tutorials, I found a bunch of small things I wanted to fix. Nothing major here.
=> Small fixes to tutorials

doc/examples/time_parameterization/time_parameterization_tutorial.rst, doc/examples/visualizing_collisions/src/visualizing_collisions_tutorial.cpp, doc/tutorials/getting_started/getting_started.rst, doc/tutorials/quickstart_in_rviz/quickstart_in_rviz_tutorial.rst
Cherry-pick the recent Cyclone recommendations to Humble branch.
=> Cherry-pick recent Cyclone recommendations to Humble

doc/tutorials/getting_started/getting_started.rst
Refer to humble instead of rolling as this confuses users: #566.
=> Fixup #560: Cyclone recommendation

doc/examples/moveit_cpp/src/moveit_cpp_tutorial.cpp, doc/how_to_guides/parallel_planning/src/parallel_planning_main.cpp
Update the API for upcoming changes in MoveIt.
Merge with https://github.com/ros-planning/moveit2/pull/1835
CI should pass when that^ MoveIt PR gets merged.
=> Do execution from moveit_cpp, add an explicit list of controllers

.github/workflows/format.yml, .pre-commit-config.yaml
https://github.com/ros-planning/moveit2/issues/1736
=> Switch to clang-format-14

conf.py
=> Don't build docs for EOL versions

.github/workflows/deploy.yml
Reference: https://github.com/ros-planning/moveit_tutorials/commit/4bcd8cca58a56316c7096ee9be92b3b488ffcbf5
@rhaschke would you mind reviewing this change?
=> Update CI deploy job

doc/examples/motion_planning_api/src/motion_planning_api_tutorial.cpp, doc/examples/motion_planning_pipeline/src/motion_planning_pipeline_tutorial.cpp, doc/examples/move_group_interface/src/move_group_interface_tutorial.cpp, doc/examples/moveit_cpp/src/moveit_cpp_tutorial.cpp, doc/examples/pilz_industrial_motion_planner/src/pilz_move_group.cpp, doc/how_to_guides/parallel_planning/src/parallel_planning_main.cpp
required to align with changes introduced by [8bfe782d6254997d185644fa3eb358d2b79d69b2](https://github.com/ros-planning/moveit2/commit/8bfe782d6254997d185644fa3eb358d2b79d69b2).
=> remove underscore from public members in MotionPlanResponse

.github/workflows/deploy.yml, conf.py, doc/examples/benchmarking/benchmarking_tutorial.rst, doc/examples/bullet_collision_checker/src/bullet_collision_checker_tutorial.cpp, doc/examples/motion_planning_api/motion_planning_api_tutorial.rst, doc/examples/motion_planning_pipeline/motion_planning_pipeline_tutorial.rst, doc/examples/pick_place/src/pick_place_tutorial.cpp, doc/examples/pilz_industrial_motion_planner/pilz_industrial_motion_planner.rst, doc/examples/planning_scene_ros_api/planning_scene_ros_api_tutorial.rst, doc/examples/planning_with_approximated_constraint_manifolds/planning_with_approximated_constraint_manifolds_tutorial.rst, doc/examples/realtime_servo/realtime_servo_tutorial.rst, htmlproofer.sh
=> htmlprofer builds with api

doc/tutorials/planning_around_objects/hello_moveit.cpp, doc/tutorials/visualizing_in_rviz/hello_moveit.cpp, doc/tutorials/visualizing_in_rviz/visualizing_in_rviz.rst
This hasn't been caught by the CI job since these files are not built with the package for some reason.
=> Fix MotionPlanResponse API

.github/workflows/docker-images.yml
=> Docker: checkout correct distro branch

build_locally.sh
This sets the moveit branch so the build works and installs doxygen and graphviz.
=> Set MOVEIT_BRANCH in build_locally.sh

.dockerignore, doc/how_to_guides/isaac_panda/.docker/Dockerfile, doc/how_to_guides/isaac_panda/.docker/ros_entrypoint.sh, doc/how_to_guides/isaac_panda/docker-compose.yaml
I was working faster than I can think yesterday and removed getting `topic_based_ros2_control` from source for the tutorial. This adds it back in and builds the workspace.
=> Patch Isaac tutorial

doc/examples/motion_planning_python_api/motion_planning_python_api_tutorial.rst
=> Fix Motion Planning Python API tutorial

doc/how_to_guides/isaac_panda/isaac_panda_tutorial.rst
I have been asked to specify `Isaac Sim` as the platform we are connecting to. Nvidia also has the Isaac platform and would like to make sure not to cause confusion.
=> Specify Isaac Sim

doc/examples/hybrid_planning/hybrid_planning_tutorial.rst
=> Use C++ code blocks for C++ code snippets

.github/workflows/deploy.yml
Fix the directory the artifact extracts to
=> Fix artifact deploy

.github/workflows/deploy.yml
Need to specify path for download.
=> Fix artifact download

doc/how_to_guides/isaac_panda/launch/python.sh
This PR change to search installed `isaac-sim` and use latest isaac-sim`.
=> use latest isaac sim for tutorial

doc/examples/jupyter_notebook_prototyping/jupyter_notebook_prototyping_tutorial.rst, doc/examples/jupyter_notebook_prototyping/src/moveit_notebook_tutorial.ipynb, doc/examples/motion_planning_python_api/motion_planning_python_api_tutorial.rst, doc/examples/motion_planning_python_api/scripts/motion_planning_python_api_planning_scene.py, doc/examples/motion_planning_python_api/scripts/motion_planning_python_api_tutorial.py, package.xml
Blocking support was removed here https://github.com/ros-planning/moveit2/pull/1984
=> Python - fix execute() API

doc/how_to_guides/pilz_industrial_motion_planner/src/pilz_move_group.cpp
Spinner thread `terminate called without an active exception`.
=> Join spinner before exit

doc/examples/examples.rst
Cleanup of a rebasing artifact
=> Remove reference to nonexisting document

doc/concepts/hybrid_planning/hybrid_planning.rst
Rephrased to avoid multiple "which".
Rephrased to avoid multiple "which" and have shorter sentences.
=> Clarify long sentence.

doc/examples/realtime_servo/realtime_servo_tutorial.rst
Document the thread priority feature of MoveIt Servo.
=> Document Servo thread priority

.github/workflows/deploy.yml
This is the first of two PRs directed at fixing this issue:
- https://github.com/ros-planning/moveit2_tutorials/issues/729
This one is kind of a do-nothing pr for the main branch because it just makes it clear what is happening. I'm going to copy much of this file over to the humble branch in a separate PR to make it behave in the same way.
=> Use main branch for deploy

.docker/Dockerfile
This was updated in #739 and then broken again by #730.
Hopefully this will fix CI on `main`.
=> Fix Hello MoveIt copy in Dockerfile

doc/examples/motion_planning_pipeline/launch/motion_planning_pipeline_tutorial.launch.py, doc/examples/motion_planning_pipeline/src/motion_planning_pipeline_tutorial.cpp, doc/how_to_guides/parallel_planning/config/parallel_planning_moveit_cpp.yaml, doc/how_to_guides/parallel_planning/launch/parallel_planning_example.launch.py, doc/how_to_guides/parallel_planning/src/parallel_planning_main.cpp, doc/how_to_guides/pilz_industrial_motion_planner/src/pilz_mtc.cpp
Depends on https://github.com/ros-planning/moveit2/pull/2288
Update tutorials to breaking changes on main introduced by https://github.com/ros-planning/moveit2/pull/2288 and address compiler warnings. 
=> Update tutorials for changes on moveit2 main

doc/how_to_guides/parallel_planning/parallel_planning_tutorial.rst, doc/how_to_guides/parallel_planning/src/parallel_planning_main.cpp
:point_up: 
Depends on https://github.com/ros-planning/moveit2/pull/2177
=> Add changes necessary to address clang tidy API breakages

doc/concepts/motion_planning.rst, doc/examples/motion_planning_api/src/motion_planning_api_tutorial.cpp, doc/examples/motion_planning_pipeline/src/motion_planning_pipeline_tutorial.cpp, doc/examples/moveit_cpp/config/moveit_cpp.yaml, doc/examples/moveit_cpp/launch/moveit_cpp_tutorial.launch.py, doc/examples/planning_adapters/planning_adapters_tutorial.rst, doc/examples/subframes/subframes_tutorial.rst, doc/examples/time_parameterization/time_parameterization_tutorial.rst, doc/how_to_guides/benchmarking/launch/run_benchmarks.launch.py, doc/how_to_guides/chomp_planner/chomp_planner_tutorial.rst, doc/how_to_guides/parallel_planning/launch/parallel_planning_example.launch.py, doc/how_to_guides/pilz_industrial_motion_planner/pilz_industrial_motion_planner.rst, doc/how_to_guides/stomp_planner/stomp_planner.rst
Depends on
- https://github.com/ros-planning/moveit2/pull/2457
- https://github.com/ros-planning/moveit_resources/pull/191
- Update tutorials to latest changes introduced by https://github.com/ros-planning/moveit2/pull/2429 and https://github.com/ros-planning/moveit2/pull/2457
=> Update tutorials to pipeline refactoring changes

doc/how_to_guides/isaac_panda/isaac_panda_tutorial.rst, doc/how_to_guides/isaac_panda/launch/python.sh
This PR updates the Isaac tutorial to support the new 2023.1.0 and 2023.1.1 release.
=> Update Isaac tutorial to support 2023.1 release

doc/how_to_guides/kinematics_cost_function/src/kinematics_cost_function_tutorial.cpp
Needed this to fix building an example on main.
=> Update to new JumpThreshold API

doc/concepts/hybrid_planning/hybrid_planning.rst
Before:
After:
Following [RST primer](https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html) for nested list:
=> Fix bullet points

doc/tutorials/pick_and_place_with_moveit_task_constructor/pick_and_place_with_moveit_task_constructor.rst
This fixes a merge  issue with `pick_and_place_with_moveit_task_constructor.rst`
=> Fix merge `pick_and_place_with_moveit_task_constructor.rst`

index.rst
=> Add moveit pro reference

.docker/README.md, README.md, doc/tutorials/your_first_project/your_first_project.rst, index.rst
While working on moveit2_tutorials, I noticed some small typos. Although they may not have a significant impact, they do make the description files look a bit unprofessional. As a result, I believe it would be better to create a pull request to fix these typos.
=> Fixing minor typos

doc/tutorials/pick_and_place_with_moveit_task_constructor/pick_and_place_with_moveit_task_constructor.rst
=> fix: ros2 launch command

requirements.txt
Doxylink with the bug fix needed was released!
See https://github.com/moveit/moveit2_tutorials/pull/1012#issuecomment-2641289624
=> Install sphinxcontrib-doxylink from released version

doc/tutorials/pick_and_place_with_moveit_task_constructor/pick_and_place_with_moveit_task_constructor.rst
Maybe this will reduce some confusion... if the humble branch was even accessible from a drop down menu instead of only from URL 😭 
=> Mention humble branch in clone commands

doc/examples/moveit_cpp/config/moveit_cpp.yaml
=> Humble: Add OMPL config to moveit_cpp.yaml
